training:
  epochs: 100
  batch_size: 2
  save_path: "workspace/transformer-transducer/saves"
  train_path : "workspace/dataset/train_w2i.json"
  dev_path : "workspace/dataset/test_w2i.json"
  test_path : "workspace/dataset/test_w2i.json"
  vocab_path : "workspace/dataset/vocab_w2i.json"
  reload: False
  log_file: "workspace/transformer-transducer/transformer_transducer_log.txt"
  


optim:
  type: adam
  lr: 0.0005
  weight_decay: 0.0001
  decay_rate: 0.5


model:
   in_features: 40
   n_enc_layers: 3
   n_dec_layers: 2
   d_model: 512
   ff_size: 1024
   h: 8
   joint_size: 1024
   p_dropout: 0.1
   model_name: "transformer_transducer"


rnnt_loss:
  blank: 4
  reduction: "mean" 

scheduler:
  # type: "LROPT" # Options: [noam, LROPT]
  lr_initial: 0.0005
  n_warmup_steps: 25000
