training:
  epochs: 100
  batch_size: 8
  save_path: "/home/anhkhoa/transformer_transducer_speeQ/save_folder"
  train_path : "/home/anhkhoa/transformer_transducer_speeQ/data/train.json"
  dev_path : "/home/anhkhoa/transformer_transducer_speeQ/data/dev.json"
  test_path : "/home/anhkhoa/transformer_transducer_speeQ/data/dev.json"
  vocab_path : "/home/anhkhoa/transformer_transducer_speeQ/data/vocab.json"
  reload: False
  log_file: "/home/anhkhoa/transformer-transducer/transformer_transducer_log.txt"
  


optim:
  type: adam
  lr: 0.001
  weight_decay: 0.0001
  decay_rate: 0.5


model:
   in_features: 80
   n_enc_layers: 1
   n_dec_layers: 1
   d_model: 64
   ff_size: 128
   h: 4
   joint_size: 128
   p_dropout: 0.1
   model_name: "transformer_transducer"


rnnt_loss:
  blank: 4
  reduction: "mean" 


