training:
  epochs: 100
  batch_size: 4
  save_path: "/home/anhkhoa/transformer_transducer_speeQ/save_folder"
  train_path : "/home/anhkhoa/transformer_transducer_speeQ/data/train_w2i.json"
  dev_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_w2i.json"
  test_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_w2i.json"
  vocab_path : "/home/anhkhoa/transformer_transducer_speeQ/data/vocab_w2i.json"
  reload: False
  log_file: "/home/anhkhoa/transformer-transducer/transformer_transducer_log.txt"
  result : "workspace/transformer-transducer/result.txt"
  type: "char" # Options: [char, phoneme]


optim:
  type: adam
  lr: 0.0005
  weight_decay: 0.0001
  decay_rate: 0.5

fbank:
  n_mels: 80
  n_fft: 512
  win_length: 25
  hop_length: 10
  sample_rate: 16000

model:
   in_features: 200
   n_enc_layers: 2
   n_dec_layers: 2
   d_model: 64
   ff_size: 128
   h: 4
   joint_size: 128
   p_dropout: 0.1
   model_name: "transformer_transducer"


rnnt_loss:
  blank: 0
  reduction: "mean" 

scheduler:
  # type: "LROPT" # Options: [noam, LROPT]
  lr_initial: 0.0005
  n_warmup_steps: 25000

